import { createFileRoute, Link } from "@tanstack/react-router";
import { Bot, CalendarCheck2, CalendarDays, Clock3, MessageCircleMore, UsersRound, Sparkles, BriefcaseBusiness, UserRoundCog, Building2, LogIn, LogOut } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";

export const Route = createFileRoute("/demo")({
  head: () => ({ meta: [{ title: "Demonstração | RecepIA" }] }),
  component: DemoPage,
});

const DEMO_EMAIL = "demo@recepia.app";
const DEMO_PASSWORD = "RecepIA2026!";

type Section = "painel" | "agenda" | "clientes" | "profissionais" | "servicos" | "conversas" | "ia" | "empresa";

function DemoPage() {
  const [logged, setLogged] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [section, setSection] = useState<Section>("painel");

  useEffect(() => { setLogged(sessionStorage.getItem("recepia-demo") === "1"); }, []);

  function login(event: FormEvent) {
    event.preventDefault();
    if (email.trim().toLowerCase() !== DEMO_EMAIL || password !== DEMO_PASSWORD) return setError("E-mail ou senha incorretos.");
    sessionStorage.setItem("recepia-demo", "1"); setLogged(true); setError("");
  }
  function logout() { sessionStorage.removeItem("recepia-demo"); setLogged(false); setEmail(""); setPassword(""); }

  if (!logged) return <main className="min-h-screen bg-[#f7f9f8] p-5 text-slate-900"><div className="mx-auto flex min-h-[90vh] max-w-md items-center"><div className="w-full rounded-[28px] border border-slate-200 bg-white p-7 shadow-xl shadow-slate-200/60"><div className="flex items-center gap-2.5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500 text-white"><Bot className="h-5 w-5"/></span><span className="font-[Sora] text-xl font-bold">Recep<span className="text-emerald-500">IA</span></span></div><p className="mt-7 text-sm font-semibold text-emerald-600">Acesso de demonstração</p><h1 className="mt-1 font-[Sora] text-3xl font-bold">Veja o sistema por dentro.</h1><p className="mt-2 text-sm leading-6 text-slate-500">Este ambiente é somente para visualização e usa dados fictícios. Nenhuma ação altera sua base real.</p><form onSubmit={login} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-sm font-semibold">E-mail</span><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-emerald-500" placeholder="demo@recepia.app"/></label><label className="block"><span className="mb-2 block text-sm font-semibold">Senha</span><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-emerald-500" placeholder="••••••••"/></label>{error && <p className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-bold text-white"><LogIn className="h-4 w-4"/>Entrar na demonstração</button></form><Link to="/" className="mt-5 block text-center text-sm font-semibold text-slate-400 hover:text-slate-700">Voltar para o site</Link></div></div></main>;

  return <main className="min-h-screen bg-[#f7f9f8] text-slate-900"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-slate-200 bg-white lg:block"><div className="flex h-18 items-center gap-2.5 border-b border-slate-100 px-6"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-500 text-white"><Bot className="h-5 w-5"/></span><span className="font-[Sora] text-xl font-bold">Recep<span className="text-emerald-500">IA</span></span></div><nav className="space-y-1 p-4 text-sm font-semibold"><DemoNav label="Painel" icon={CalendarDays} active={section==="painel"} onClick={()=>setSection("painel")}/><DemoNav label="Agenda" icon={CalendarCheck2} active={section==="agenda"} onClick={()=>setSection("agenda")}/><DemoNav label="Clientes" icon={UsersRound} active={section==="clientes"} onClick={()=>setSection("clientes")}/><DemoNav label="Profissionais" icon={UserRoundCog} active={section==="profissionais"} onClick={()=>setSection("profissionais")}/><DemoNav label="Serviços" icon={BriefcaseBusiness} active={section==="servicos"} onClick={()=>setSection("servicos")}/><DemoNav label="Conversas" icon={MessageCircleMore} active={section==="conversas"} onClick={()=>setSection("conversas")}/><DemoNav label="Configuração da IA" icon={Sparkles} active={section==="ia"} onClick={()=>setSection("ia")}/><DemoNav label="Empresa" icon={Building2} active={section==="empresa"} onClick={()=>setSection("empresa")}/></nav><button onClick={logout} className="absolute bottom-5 left-4 right-4 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-500 hover:bg-slate-100"><LogOut className="h-4 w-4"/>Sair da demo</button></aside><div className="lg:pl-64"><header className="flex h-18 items-center justify-between border-b border-slate-200 bg-white px-5 sm:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-slate-400">Demonstração</p><p className="font-semibold">Clínica Horizonte</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">Modo somente leitura</span></header><div className="mx-auto max-w-7xl p-5 sm:p-8">{section === "painel" ? <DashboardDemo/> : <SectionDemo section={section}/>}</div></div></main>;
}

function DemoNav({label,icon:Icon,active,onClick}:{label:string;icon:typeof CalendarDays;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left ${active?"bg-emerald-50 text-emerald-700":"text-slate-500 hover:bg-slate-50"}`}><Icon className="h-4 w-4"/>{label}</button>}
function DashboardDemo(){return <><div><p className="text-sm font-semibold text-emerald-600">Visão geral</p><h1 className="mt-1 font-[Sora] text-3xl font-bold">Bom trabalho hoje.</h1><p className="mt-2 text-sm text-slate-500">Dados fictícios para você visualizar o painel.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={CalendarCheck2} label="Agendamentos hoje" value="12"/><Stat icon={UsersRound} label="Clientes cadastrados" value="248"/><Stat icon={MessageCircleMore} label="Conversas hoje" value="31"/><Stat icon={Bot} label="Agendamentos pela IA" value="8" accent/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-[Sora] text-lg font-semibold">Atividade recente</h2><div className="mt-5 divide-y divide-slate-100">{[["Mariana Souza","Consulta","09:30"],["Carlos Lima","Retorno","11:00"],["Ana Ribeiro","Avaliação","14:30"]].map(([name,service,time])=><div key={name} className="flex items-center justify-between py-4"><div><p className="text-sm font-semibold">{name}</p><p className="text-xs text-slate-500">{service}</p></div><span className="text-sm font-semibold text-slate-600">{time}</span></div>)}</div></section><section className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-500"><Bot className="h-5 w-5"/></div><h2 className="mt-6 font-[Sora] text-xl font-semibold">IA trabalhando</h2><p className="mt-2 text-sm leading-6 text-slate-400">A recepcionista virtual está atendendo clientes e consultando a agenda.</p><div className="mt-6 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-slate-400">Taxa de agendamento</p><p className="mt-2 text-3xl font-bold text-emerald-400">25,8%</p></div></section></div></>}
function Stat({icon:Icon,label,value,accent=false}:{icon:typeof CalendarDays;label:string;value:string;accent?:boolean}){return <article className={`rounded-3xl border p-5 ${accent?"border-emerald-200 bg-emerald-50":"border-slate-200 bg-white"}`}><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${accent?"bg-emerald-500 text-white":"bg-slate-100 text-slate-600"}`}><Icon className="h-4 w-4"/></div><p className="mt-5 text-sm text-slate-500">{label}</p><p className="mt-1 font-[Sora] text-3xl font-bold">{value}</p></article>}
function SectionDemo({section}:{section:Exclude<Section,"painel">}){const content:Record<string,{title:string;subtitle:string;items:string[]}>= {agenda:{title:"Agenda",subtitle:"Visualização dos compromissos e horários.",items:["09:30 — Mariana Souza — Consulta","11:00 — Carlos Lima — Retorno","14:30 — Ana Ribeiro — Avaliação"]},clientes:{title:"Clientes",subtitle:"Base de clientes da empresa.",items:["Mariana Souza — Ativo","Carlos Lima — Ativo","Ana Ribeiro — Novo"]},profissionais:{title:"Profissionais",subtitle:"Equipe cadastrada.",items:["Dra. Camila Rocha — Clínica Geral","Dr. Rafael Mendes — Atendimento","Juliana Alves — Recepção"]},servicos:{title:"Serviços",subtitle:"Serviços disponíveis para agendamento.",items:["Consulta — 45 min — R$ 150,00","Retorno — 30 min — R$ 90,00","Avaliação — 40 min — R$ 120,00"]},conversas:{title:"Conversas",subtitle:"Atendimentos recentes da IA.",items:["Mariana — IA — horário confirmado","Carlos — Humano — aguardando resposta","Ana — IA — consultando disponibilidade"]},ia:{title:"Configuração da IA",subtitle:"Personalidade e regras da recepcionista.",items:["Nome: Júlia","Tom: Amigável","Status: Ativa"]},empresa:{title:"Empresa e instalação",subtitle:"Dados e canal público.",items:["Clínica Horizonte","São Paulo - SP","Chat público configurado"]}};const c=content[section];return <><p className="text-sm font-semibold text-emerald-600">Demonstração</p><h1 className="mt-1 font-[Sora] text-3xl font-bold">{c.title}</h1><p className="mt-2 text-sm text-slate-500">{c.subtitle}</p><div className="mt-7 rounded-3xl border border-slate-200 bg-white p-6"><div className="divide-y divide-slate-100">{c.items.map((item)=><div key={item} className="py-4 text-sm font-medium text-slate-700">{item}</div>)}</div></div></>}
