import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Bot, CheckCircle2, Clipboard, Loader2, MessageCircleMore, ShieldCheck, Unplug, Webhook } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

export const Route = createFileRoute("/integracoes")({ head: () => ({ meta: [{ title: "Integrações | RecepIA" }] }), component: IntegrationsPage });

type Integration = { id:string; status:string; config:any; connected_at:string|null; last_event_at:string|null; last_test_at:string|null; last_error:string|null };

function IntegrationsPage(){
  const navigate=useNavigate();
  const {user,organizationId,loading}=useAuth();
  const [integration,setIntegration]=useState<Integration|null>(null);
  const [form,setForm]=useState({phoneNumberId:"",wabaId:"",accessToken:"",appSecret:"",autoReplyMessage:"Olá! 👋 Para falar com nossa recepcionista virtual e consultar horários disponíveis, acesse o link abaixo:"});
  const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [copied,setCopied]=useState(""); const [origin,setOrigin]=useState("");
  useEffect(()=>{if(typeof window!=="undefined")setOrigin(window.location.origin)},[]);
  useEffect(()=>{if(loading)return;if(!user)return void navigate({to:"/login"});if(!organizationId)return void navigate({to:"/onboarding"});void load()},[loading,user,organizationId]);
  async function load(){if(!organizationId)return;const {data}=await supabase.from("integrations").select("id,status,config,connected_at,last_event_at,last_test_at,last_error").eq("organization_id",organizationId).eq("provider","whatsapp_cloud").maybeSingle();setIntegration((data as Integration|null)??null);if(data?.config?.auto_reply_message)setForm(v=>({...v,autoReplyMessage:data.config.auto_reply_message}))}
  async function connect(e:React.FormEvent){e.preventDefault();if(!organizationId||!origin)return;setSaving(true);setError("");const {data,error:invokeError}=await supabase.functions.invoke("integration-manager",{body:{action:"connect",organizationId,publicBaseUrl:origin,...form}});if(invokeError||data?.error)setError(data?.error||invokeError?.message||"Não foi possível conectar o WhatsApp.");else{setForm(v=>({...v,accessToken:"",appSecret:""}));await load()}setSaving(false)}
  async function disconnect(){if(!organizationId||!confirm("Desconectar o WhatsApp desta empresa?"))return;setSaving(true);const {data,error:invokeError}=await supabase.functions.invoke("integration-manager",{body:{action:"disconnect",organizationId}});if(invokeError||data?.error)setError(data?.error||invokeError?.message||"Falha ao desconectar");else setIntegration(null);setSaving(false)}
  async function copy(value:string,key:string){if(!value)return;await navigator.clipboard.writeText(value);setCopied(key);setTimeout(()=>setCopied(""),1500)}
  const webhookUrl=useMemo(()=>integration?.config?.webhook_key?`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/whatsapp-webhook?key=${encodeURIComponent(integration.config.webhook_key)}`:"",[integration]);
  const verifyToken=integration?.config?.verify_token||""; const connected=integration?.status==="conectado"&&integration?.config?.webhook_verified===true;
  return <main className="min-h-screen bg-[#f7f9f8] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/dashboard" className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-500 text-white"><Bot className="h-5 w-5"/></span><span className="font-[Sora] text-xl font-bold">Recep<span className="text-emerald-500">IA</span></span></Link><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="h-4 w-4"/>Voltar ao painel</Link></div></header><div className="mx-auto max-w-7xl p-5 sm:p-8"><div><p className="text-sm font-semibold text-emerald-600">Integrações</p><h1 className="mt-1 font-[Sora] text-3xl font-bold">Conecte o WhatsApp ao atendimento automático.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Quando um cliente enviar uma mensagem, a RecepIA responde com o link exclusivo da recepcionista virtual. Pelo link ele conversa com a IA, consulta a agenda real e confirma o horário.</p></div>
  <section className="mt-7 rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600"><MessageCircleMore className="h-5 w-5"/></span><div><h2 className="font-[Sora] text-lg font-semibold">WhatsApp Cloud API</h2><p className="text-sm text-slate-500">Integração oficial da Meta para receber mensagens e disparar o link automaticamente.</p></div></div><span className={`rounded-full px-4 py-2 text-xs font-bold ${connected?"bg-emerald-500 text-white":"bg-slate-100 text-slate-600"}`}>{connected?"Conectado":integration?"Aguardando webhook":"Não conectado"}</span></div>
  {integration?<div className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h3 className="font-semibold">Dados da conexão</h3><div className="mt-4 space-y-2 text-sm text-slate-600"><p><b>Número:</b> {integration.config?.display_phone_number||"Validado"}</p><p><b>Conta:</b> {integration.config?.verified_name||"WhatsApp Business"}</p><p><b>Último evento:</b> {integration.last_event_at?new Date(integration.last_event_at).toLocaleString("pt-BR"):"Ainda não recebido"}</p>{integration.last_error&&<p className="text-red-600"><b>Erro:</b> {integration.last_error}</p>}</div><button disabled={saving} onClick={disconnect} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-red-200 bg-white px-4 py-2.5 text-sm font-bold text-red-600"><Unplug className="h-4 w-4"/>Desconectar</button></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 text-emerald-800"><Webhook className="h-5 w-5"/><h3 className="font-semibold">Ativar webhook na Meta</h3></div><p className="mt-2 text-sm leading-6 text-emerald-900/70">No painel Meta Developers, configure estes dois valores e assine o campo <b>messages</b>.</p><CopyField label="Callback URL" value={webhookUrl} copied={copied==="url"} onCopy={()=>copy(webhookUrl,"url")}/><CopyField label="Verify token" value={verifyToken} copied={copied==="token"} onCopy={()=>copy(verifyToken,"token")}/>{connected?<p className="mt-4 flex items-center gap-2 text-sm font-bold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Webhook verificado. O disparo automático está ativo.</p>:<p className="mt-4 text-sm font-semibold text-amber-700">Depois de clicar em “Verificar e salvar” na Meta, atualize esta página.</p>}</div></div>:
  <form onSubmit={connect} className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Phone Number ID" value={form.phoneNumberId} onChange={v=>setForm({...form,phoneNumberId:v})}/><Field label="WhatsApp Business Account ID (WABA)" value={form.wabaId} onChange={v=>setForm({...form,wabaId:v})}/><Field label="Access Token permanente" type="password" value={form.accessToken} onChange={v=>setForm({...form,accessToken:v})}/><Field label="App Secret" type="password" value={form.appSecret} onChange={v=>setForm({...form,appSecret:v})}/><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Mensagem automática</span><textarea value={form.autoReplyMessage} onChange={e=>setForm({...form,autoReplyMessage:e.target.value})} className="min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500"/><p className="mt-2 text-xs text-slate-400">O link personalizado do assistente é acrescentado automaticamente no final.</p></label>{error&&<div className="sm:col-span-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<button disabled={saving} className="sm:col-span-2 inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-bold text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<ShieldCheck className="h-4 w-4"/>}{saving?"Validando conexão...":"Conectar WhatsApp com segurança"}</button></form>}
  </section><section className="mt-6 grid gap-4 md:grid-cols-4">{["Cliente envia mensagem no WhatsApp","Webhook identifica empresa e cliente","RecepIA envia o link exclusivo","IA conversa e agenda automaticamente"].map((text,i)=><div key={text} className="rounded-2xl border border-slate-200 bg-white p-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-500 text-xs font-bold text-white">{i+1}</span><p className="mt-3 text-sm font-semibold leading-6">{text}</p></div>)}</section></div></main>}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span className="mb-2 block text-sm font-semibold">{label}</span><input required type={type} value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-emerald-500"/></label>}
function CopyField({label,value,copied,onCopy}:{label:string;value:string;copied:boolean;onCopy:()=>void}){return <div className="mt-4"><p className="text-xs font-bold uppercase tracking-wide text-emerald-800/60">{label}</p><div className="mt-1 flex gap-2"><input readOnly value={value} className="h-10 min-w-0 flex-1 rounded-xl border border-emerald-200 bg-white px-3 text-xs"/><button onClick={onCopy} className="flex h-10 w-10 items-center justify-center rounded-xl border border-emerald-200 bg-white" type="button"><Clipboard className="h-4 w-4"/></button></div>{copied&&<span className="mt-1 block text-xs font-bold text-emerald-700">Copiado</span>}</div>}
