/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracaoIaRouteImport } from './routes/configuracao-ia'
import { Route as ConfiguracoesEmpresaRouteImport } from './routes/configuracoes-empresa'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ChatSlugRouteImport } from './routes/chat.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoIaRoute = ConfiguracaoIaRouteImport.update({
  id: '/configuracao-ia',
  path: '/configuracao-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesEmpresaRoute = ConfiguracoesEmpresaRouteImport.update({
  id: '/configuracoes-empresa',
  path: '/configuracoes-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSlugRoute = ChatSlugRouteImport.update({
  id: '/chat/$slug',
  path: '/chat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracao-ia': typeof ConfiguracaoIaRoute
  '/configuracoes-empresa': typeof ConfiguracoesEmpresaRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/horarios': typeof HorariosRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/profissionais': typeof ProfissionaisRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/termos': typeof TermosRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracao-ia': typeof ConfiguracaoIaRoute
  '/configuracoes-empresa': typeof ConfiguracoesEmpresaRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/horarios': typeof HorariosRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/profissionais': typeof ProfissionaisRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/termos': typeof TermosRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracao-ia': typeof ConfiguracaoIaRoute
  '/configuracoes-empresa': typeof ConfiguracoesEmpresaRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/horarios': typeof HorariosRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/profissionais': typeof ProfissionaisRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/servicos': typeof ServicosRoute
  '/termos': typeof TermosRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/ajuda'
    | '/assinatura'
    | '/cadastro'
    | '/clientes'
    | '/configuracao-ia'
    | '/configuracoes-empresa'
    | '/conversas'
    | '/dashboard'
    | '/demo'
    | '/horarios'
    | '/integracoes'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/profissionais'
    | '/recuperar-senha'
    | '/relatorios'
    | '/servicos'
    | '/termos'
    | '/chat/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/ajuda'
    | '/assinatura'
    | '/cadastro'
    | '/clientes'
    | '/configuracao-ia'
    | '/configuracoes-empresa'
    | '/conversas'
    | '/dashboard'
    | '/demo'
    | '/horarios'
    | '/integracoes'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/profissionais'
    | '/recuperar-senha'
    | '/relatorios'
    | '/servicos'
    | '/termos'
    | '/chat/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/ajuda'
    | '/assinatura'
    | '/cadastro'
    | '/clientes'
    | '/configuracao-ia'
    | '/configuracoes-empresa'
    | '/conversas'
    | '/dashboard'
    | '/demo'
    | '/horarios'
    | '/integracoes'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/profissionais'
    | '/recuperar-senha'
    | '/relatorios'
    | '/servicos'
    | '/termos'
    | '/chat/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AjudaRoute: typeof AjudaRoute
  AssinaturaRoute: typeof AssinaturaRoute
  CadastroRoute: typeof CadastroRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracaoIaRoute: typeof ConfiguracaoIaRoute
  ConfiguracoesEmpresaRoute: typeof ConfiguracoesEmpresaRoute
  ConversasRoute: typeof ConversasRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  HorariosRoute: typeof HorariosRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ServicosRoute: typeof ServicosRoute
  TermosRoute: typeof TermosRoute
  ChatSlugRoute: typeof ChatSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao-ia': {
      id: '/configuracao-ia'
      path: '/configuracao-ia'
      fullPath: '/configuracao-ia'
      preLoaderRoute: typeof ConfiguracaoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-empresa': {
      id: '/configuracoes-empresa'
      path: '/configuracoes-empresa'
      fullPath: '/configuracoes-empresa'
      preLoaderRoute: typeof ConfiguracoesEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$slug': {
      id: '/chat/$slug'
      path: '/chat/$slug'
      fullPath: '/chat/$slug'
      preLoaderRoute: typeof ChatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AjudaRoute: AjudaRoute,
  AssinaturaRoute: AssinaturaRoute,
  CadastroRoute: CadastroRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracaoIaRoute: ConfiguracaoIaRoute,
  ConfiguracoesEmpresaRoute: ConfiguracoesEmpresaRoute,
  ConversasRoute: ConversasRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  HorariosRoute: HorariosRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  OnboardingRoute: OnboardingRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  ServicosRoute: ServicosRoute,
  TermosRoute: TermosRoute,
  ChatSlugRoute: ChatSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
