/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It may be regenerated by the router plugin during the next build.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ConfiguracaoIaRouteImport } from './routes/configuracao-ia'
import { Route as ConfiguracoesEmpresaRouteImport } from './routes/configuracoes-empresa'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ChatSlugRouteImport } from './routes/chat.$slug'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const CadastroRoute = CadastroRouteImport.update({ id: '/cadastro', path: '/cadastro', getParentRoute: () => rootRouteImport } as any)
const OnboardingRoute = OnboardingRouteImport.update({ id: '/onboarding', path: '/onboarding', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const AgendaRoute = AgendaRouteImport.update({ id: '/agenda', path: '/agenda', getParentRoute: () => rootRouteImport } as any)
const ClientesRoute = ClientesRouteImport.update({ id: '/clientes', path: '/clientes', getParentRoute: () => rootRouteImport } as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({ id: '/profissionais', path: '/profissionais', getParentRoute: () => rootRouteImport } as any)
const ServicosRoute = ServicosRouteImport.update({ id: '/servicos', path: '/servicos', getParentRoute: () => rootRouteImport } as any)
const ConversasRoute = ConversasRouteImport.update({ id: '/conversas', path: '/conversas', getParentRoute: () => rootRouteImport } as any)
const ConfiguracaoIaRoute = ConfiguracaoIaRouteImport.update({ id: '/configuracao-ia', path: '/configuracao-ia', getParentRoute: () => rootRouteImport } as any)
const ConfiguracoesEmpresaRoute = ConfiguracoesEmpresaRouteImport.update({ id: '/configuracoes-empresa', path: '/configuracoes-empresa', getParentRoute: () => rootRouteImport } as any)
const HorariosRoute = HorariosRouteImport.update({ id: '/horarios', path: '/horarios', getParentRoute: () => rootRouteImport } as any)
const RelatoriosRoute = RelatoriosRouteImport.update({ id: '/relatorios', path: '/relatorios', getParentRoute: () => rootRouteImport } as any)
const AssinaturaRoute = AssinaturaRouteImport.update({ id: '/assinatura', path: '/assinatura', getParentRoute: () => rootRouteImport } as any)
const DemoRoute = DemoRouteImport.update({ id: '/demo', path: '/demo', getParentRoute: () => rootRouteImport } as any)
const ChatSlugRoute = ChatSlugRouteImport.update({ id: '/chat/$slug', path: '/chat/$slug', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastro': typeof CadastroRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof DashboardRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/conversas': typeof ConversasRoute
  '/configuracao-ia': typeof ConfiguracaoIaRoute
  '/configuracoes-empresa': typeof ConfiguracoesEmpresaRoute
  '/horarios': typeof HorariosRoute
  '/relatorios': typeof RelatoriosRoute
  '/assinatura': typeof AssinaturaRoute
  '/demo': typeof DemoRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastro': typeof CadastroRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof DashboardRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/conversas': typeof ConversasRoute
  '/configuracao-ia': typeof ConfiguracaoIaRoute
  '/configuracoes-empresa': typeof ConfiguracoesEmpresaRoute
  '/horarios': typeof HorariosRoute
  '/relatorios': typeof RelatoriosRoute
  '/assinatura': typeof AssinaturaRoute
  '/demo': typeof DemoRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/cadastro' | '/onboarding' | '/dashboard' | '/agenda' | '/clientes' | '/profissionais' | '/servicos' | '/conversas' | '/configuracao-ia' | '/configuracoes-empresa' | '/horarios' | '/relatorios' | '/assinatura' | '/demo' | '/chat/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: FileRouteTypes['fullPaths']
  id: '__root__' | FileRouteTypes['fullPaths']
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CadastroRoute: typeof CadastroRoute
  OnboardingRoute: typeof OnboardingRoute
  DashboardRoute: typeof DashboardRoute
  AgendaRoute: typeof AgendaRoute
  ClientesRoute: typeof ClientesRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  ServicosRoute: typeof ServicosRoute
  ConversasRoute: typeof ConversasRoute
  ConfiguracaoIaRoute: typeof ConfiguracaoIaRoute
  ConfiguracoesEmpresaRoute: typeof ConfiguracoesEmpresaRoute
  HorariosRoute: typeof HorariosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  AssinaturaRoute: typeof AssinaturaRoute
  DemoRoute: typeof DemoRoute
  ChatSlugRoute: typeof ChatSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/cadastro': { id: '/cadastro'; path: '/cadastro'; fullPath: '/cadastro'; preLoaderRoute: typeof CadastroRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding': { id: '/onboarding'; path: '/onboarding'; fullPath: '/onboarding'; preLoaderRoute: typeof OnboardingRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/agenda': { id: '/agenda'; path: '/agenda'; fullPath: '/agenda'; preLoaderRoute: typeof AgendaRouteImport; parentRoute: typeof rootRouteImport }
    '/clientes': { id: '/clientes'; path: '/clientes'; fullPath: '/clientes'; preLoaderRoute: typeof ClientesRouteImport; parentRoute: typeof rootRouteImport }
    '/profissionais': { id: '/profissionais'; path: '/profissionais'; fullPath: '/profissionais'; preLoaderRoute: typeof ProfissionaisRouteImport; parentRoute: typeof rootRouteImport }
    '/servicos': { id: '/servicos'; path: '/servicos'; fullPath: '/servicos'; preLoaderRoute: typeof ServicosRouteImport; parentRoute: typeof rootRouteImport }
    '/conversas': { id: '/conversas'; path: '/conversas'; fullPath: '/conversas'; preLoaderRoute: typeof ConversasRouteImport; parentRoute: typeof rootRouteImport }
    '/configuracao-ia': { id: '/configuracao-ia'; path: '/configuracao-ia'; fullPath: '/configuracao-ia'; preLoaderRoute: typeof ConfiguracaoIaRouteImport; parentRoute: typeof rootRouteImport }
    '/configuracoes-empresa': { id: '/configuracoes-empresa'; path: '/configuracoes-empresa'; fullPath: '/configuracoes-empresa'; preLoaderRoute: typeof ConfiguracoesEmpresaRouteImport; parentRoute: typeof rootRouteImport }
    '/horarios': { id: '/horarios'; path: '/horarios'; fullPath: '/horarios'; preLoaderRoute: typeof HorariosRouteImport; parentRoute: typeof rootRouteImport }
    '/relatorios': { id: '/relatorios'; path: '/relatorios'; fullPath: '/relatorios'; preLoaderRoute: typeof RelatoriosRouteImport; parentRoute: typeof rootRouteImport }
    '/assinatura': { id: '/assinatura'; path: '/assinatura'; fullPath: '/assinatura'; preLoaderRoute: typeof AssinaturaRouteImport; parentRoute: typeof rootRouteImport }
    '/demo': { id: '/demo'; path: '/demo'; fullPath: '/demo'; preLoaderRoute: typeof DemoRouteImport; parentRoute: typeof rootRouteImport }
    '/chat/$slug': { id: '/chat/$slug'; path: '/chat/$slug'; fullPath: '/chat/$slug'; preLoaderRoute: typeof ChatSlugRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  LoginRoute,
  CadastroRoute,
  OnboardingRoute,
  DashboardRoute,
  AgendaRoute,
  ClientesRoute,
  ProfissionaisRoute,
  ServicosRoute,
  ConversasRoute,
  ConfiguracaoIaRoute,
  ConfiguracoesEmpresaRoute,
  HorariosRoute,
  RelatoriosRoute,
  AssinaturaRoute,
  DemoRoute,
  ChatSlugRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
